export const kougoBibleMap: {
  [key: string]: { name: string; category: string };
} = {
  Genesis: { name: "創世記", category: "律法書" },
  Exodus: { name: "出エジプト記", category: "律法書" },
  Leviticus: { name: "レビ記", category: "律法書" },
  Numbers: { name: "民数記", category: "律法書" },
  Deuteronomy: { name: "申命記", category: "律法書" },
  Joshua: { name: "ヨシュア記", category: "歴史書" },
  Judges: { name: "士師記", category: "歴史書" },
  Ruth: { name: "ルツ記", category: "歴史書" },
  "I Samuel": { name: "サムエル記第一", category: "歴史書" },
  "II Samuel": { name: "サムエル記第二", category: "歴史書" },
  "I Kings": { name: "列王記第一", category: "歴史書" },
  "II Kings": { name: "列王記第二", category: "歴史書" },
  "I Chronicles": { name: "歴代誌第一", category: "歴史書" },
  "II Chronicles": { name: "歴代誌第二", category: "歴史書" },
  Ezra: { name: "エズラ記", category: "歴史書" },
  Nehemiah: { name: "ネヘミヤ記", category: "歴史書" },
  Esther: { name: "エステル記", category: "歴史書" },
  Job: { name: "ヨブ記", category: "詩歌・知恵書" },
  Psalms: { name: "詩篇", category: "詩歌・知恵書" },
  Proverbs: { name: "箴言", category: "詩歌・知恵書" },
  Ecclesiastes: { name: "伝道者の書", category: "詩歌・知恵書" },
  "Song of Solomon": { name: "雅歌", category: "詩歌・知恵書" },
  Isaiah: { name: "イザヤ書", category: "預言書" },
  Jeremiah: { name: "エレミヤ書", category: "預言書" },
  Lamentations: { name: "哀歌", category: "預言書" },
  Ezekiel: { name: "エゼキエル書", category: "預言書" },
  Daniel: { name: "ダニエル書", category: "預言書" },
  Hosea: { name: "ホセア書", category: "預言書" },
  Joel: { name: "ヨエル書", category: "預言書" },
  Amos: { name: "アモス書", category: "預言書" },
  Obadiah: { name: "オバデヤ書", category: "預言書" },
  Jonah: { name: "ヨナ書", category: "預言書" },
  Micah: { name: "ミカ書", category: "預言書" },
  Nahum: { name: "ナホム書", category: "預言書" },
  Habakkuk: { name: "ハバクク書", category: "預言書" },
  Zephaniah: { name: "ゼパニヤ書", category: "預言書" },
  Haggai: { name: "ハガイ書", category: "預言書" },
  Zechariah: { name: "ゼカリヤ書", category: "預言書" },
  Malachi: { name: "マラキ書", category: "預言書" },
  Matthew: { name: "マタイの福音書", category: "福音書" },
  Mark: { name: "マルコの福音書", category: "福音書" },
  Luke: { name: "ルカの福音書", category: "福音書" },
  John: { name: "ヨハネの福音書", category: "福音書" },
  Acts: { name: "使徒の働き", category: "歴史書" },
  Romans: { name: "ローマ人への手紙", category: "パウロ書簡" },
  "I Corinthians": { name: "コリント人への手紙第一", category: "パウロ書簡" },
  "II Corinthians": { name: "コリント人への手紙第二", category: "パウロ書簡" },
  Galatians: { name: "ガラテヤ人への手紙", category: "パウロ書簡" },
  Ephesians: { name: "エペソ人への手紙", category: "パウロ書簡" },
  Philippians: { name: "ピリピ人への手紙", category: "パウロ書簡" },
  Colossians: { name: "コロサイ人への手紙", category: "パウロ書簡" },
  "I Thessalonians": {
    name: "テサロニケ人への手紙第一",
    category: "パウロ書簡",
  },
  "II Thessalonians": {
    name: "テサロニケ人への手紙第二",
    category: "パウロ書簡",
  },
  "I Timothy": { name: "テモテへの手紙第一", category: "パウロ書簡" },
  "II Timothy": { name: "テモテへの手紙第二", category: "パウロ書簡" },
  Titus: { name: "テトスへの手紙", category: "パウロ書簡" },
  Philemon: { name: "ピレモンへの手紙", category: "パウロ書簡" },
  Hebrews: { name: "ヘブル人への手紙", category: "一般書簡" },
  James: { name: "ヤコブの手紙", category: "一般書簡" },
  "I Peter": { name: "ペテロの手紙第一", category: "一般書簡" },
  "II Peter": { name: "ペテロの手紙第二", category: "一般書簡" },
  "I John": { name: "ヨハネの手紙第一", category: "一般書簡" },
  "II John": { name: "ヨハネの手紙第二", category: "一般書簡" },
  "III John": { name: "ヨハネの手紙第三", category: "一般書簡" },
  Jude: { name: "ユダの手紙", category: "一般書簡" },
  "Revelation of John": { name: "ヨハネの黙示録", category: "黙示文学" },
};
